+incdir+../rtl/lm32_top/rtl/verilog/
../rtl/lm32_top/rtl/verilog/JTAGB.v
../rtl/lm32_top/rtl/verilog/lm32_adder.v
../rtl/lm32_top/rtl/verilog/lm32_dcache.v


../rtl/lm32_top/rtl/verilog/lm32_jtag.v
../rtl/lm32_top/rtl/verilog/lm32_mc_arithmetic.v
../rtl/lm32_top/rtl/verilog/lm32_multiplier.v
../rtl/lm32_top/rtl/verilog/lm32_top.v    
../rtl/lm32_top/rtl/verilog/jtag_cores.v
../rtl/lm32_top/rtl/verilog/lm32_addsub.v
../rtl/lm32_top/rtl/verilog/lm32_debug.v
../rtl/lm32_top/rtl/verilog/lm32_icache.v
../rtl/lm32_top/rtl/verilog/lm32_instruction_unit.v
../rtl/lm32_top/rtl/verilog/lm32_load_store_unit.v
../rtl/lm32_top/rtl/verilog/lm32_monitor.v
../rtl/lm32_top/rtl/verilog/lm32_ram.v
../rtl/lm32_top/rtl/verilog/lm32_trace.v
../rtl/lm32_top/rtl/verilog/typea.v
../rtl/lm32_top/rtl/verilog/jtag_lm32.v
../rtl/lm32_top/rtl/verilog/lm32_cpu.v
../rtl/lm32_top/rtl/verilog/lm32_decoder.v
../rtl/lm32_top/rtl/verilog/lm32_interrupt.v
../rtl/lm32_top/rtl/verilog/lm32_logic_op.v
../rtl/lm32_top/rtl/verilog/lm32_monitor_ram.v
../rtl/lm32_top/rtl/verilog/lm32_shifter.v
../rtl/lm32_top/rtl/verilog/spiprog.v
../rtl/lm32_top/rtl/verilog/typeb.v
