
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_bus_if_wb32.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_decode_execute_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_pic.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_true_dpram_sclk.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx-sprs.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_cache_lru.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_ctrl_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_dmmu.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_rf_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_wb_mux_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx.v +incdir+../rtl/MOR1KX/rtl/verilog/
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_cfgrs.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_execute_alu.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_icache.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_branch_prediction.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_cpu.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_immu.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_simple_dpram_sclk.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_cpu_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_dcache.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_fetch_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_lsu_cappuccino.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_store_buffer.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_branch_predictor_simple.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_decode.v
vlog ../rtl/MOR1KX/rtl/verilog/mor1kx_ticktimer.v
