+incdir+../rtl/MOR1KX/rtl/verilog/

../rtl/MOR1KX/rtl/verilog/mor1kx-defines.v
../rtl/MOR1KX/rtl/verilog/mor1kx_bus_if_wb32.v
../rtl/MOR1KX/rtl/verilog/mor1kx_decode_execute_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_pic.v
../rtl/MOR1KX/rtl/verilog/mor1kx_true_dpram_sclk.v
../rtl/MOR1KX/rtl/verilog/mor1kx-sprs.v
../rtl/MOR1KX/rtl/verilog/mor1kx_cache_lru.v
../rtl/MOR1KX/rtl/verilog/mor1kx_ctrl_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_dmmu.v
../rtl/MOR1KX/rtl/verilog/mor1kx_rf_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_wb_mux_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx.v
../rtl/MOR1KX/rtl/verilog/mor1kx_cfgrs.v
../rtl/MOR1KX/rtl/verilog/mor1kx_execute_alu.v
../rtl/MOR1KX/rtl/verilog/mor1kx_icache.v
../rtl/MOR1KX/rtl/verilog/mor1kx_branch_prediction.v
../rtl/MOR1KX/rtl/verilog/mor1kx_cpu.v
../rtl/MOR1KX/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_immu.v
../rtl/MOR1KX/rtl/verilog/mor1kx_simple_dpram_sclk.v
../rtl/MOR1KX/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
../rtl/MOR1KX/rtl/verilog/mor1kx_cpu_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_dcache.v
../rtl/MOR1KX/rtl/verilog/mor1kx_fetch_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_lsu_cappuccino.v
../rtl/MOR1KX/rtl/verilog/mor1kx_store_buffer.v
../rtl/MOR1KX/rtl/verilog/mor1kx_branch_predictor_simple.v
../rtl/MOR1KX/rtl/verilog/mor1kx_decode.v
../rtl/MOR1KX/rtl/verilog/mor1kx_ticktimer.v
