
vlog ../rtl/LM32/rtl/jtag_cores.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_adder.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_dcache.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_decoder.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_dtlb.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_interrupt.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_jtag.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/jtag_tap_spartan6.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/BSCAN_SPARTAN6.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/glbl.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_logic_op.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_multiplier.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_shifter.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_addsub.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_cpu.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_debug.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_dp_ram.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_icache.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_instruction_unit.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_itlb.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_load_store_unit.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_mc_arithmetic.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_ram.v +incdir+../rtl/cpu
vlog ../rtl/LM32/rtl/lm32_top.v +incdir+../rtl/cpu
