../rtl/system_controller/system_controller_xilinx.v
../rtl/XILINX/BUFGCE.v
../rtl/XILINX/glbl.v
../rtl/XILINX/IBUF.v
../rtl/XILINX/MMCME2_BASE.v
../rtl/XILINX/MMCME2_ADV.v
../rtl/XILINX/RAMB16_S9.v
../rtl/wb_ram/rtl/verilog/wb_ram_xilinx_bank.v
../rtl/wb_ram/rtl/verilog/wb_ram_xilinx.v
