// 
// Do not edit this file, it is automatically generated!
// To generate this file, "make design.h" in the rtl directory.
// 
#ifndef DESIGN_H
#define DESIGN_H

#define	INCLUDE_ZIPCPU
#define	WBUBUS_MASTER
#define	BUSCONSOLE_ACCESS
#define	FLASH_ACCESS
#define	BUSPIC_ACCESS
#define	RTC_ACCESS
#define	BLKRAM_ACCESS
#define	FLASH_ACCESS
#define	SDSPI_ACCESS
#ifdef	RTC_ACCESS
#define	RTCDATE_ACCESS
#endif
#ifdef	SDSPI_ACCESS
#define	SDSPI_SCOPE
#endif
#ifndef	INCLUDE_ZIPCPU
#endif
#ifdef	VERILATOR
#else	// VERILATOR
#endif	// VERILATOR
#ifdef	BUSCONSOLE_ACCESS
#else	// BUSCONSOLE_ACCESS
#endif	// BUSCONSOLE_ACCESS
#ifdef	FLASH_ACCESS
#else	// FLASH_ACCESS
#endif	// FLASH_ACCESS
#ifdef	BUSPIC_ACCESS
#else	// BUSPIC_ACCESS
#endif	// BUSPIC_ACCESS
#ifdef	WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#define	BUS_DELAY_NEEDED
#endif
#endif
#ifdef	BUS_DELAY_NEEDED
#else
#endif
#ifdef	RTC_ACCESS
#else	// RTC_ACCESS
#endif	// RTC_ACCESS
#ifdef	BLKRAM_ACCESS
#else	// BLKRAM_ACCESS
#endif	// BLKRAM_ACCESS
#ifdef	FLASH_ACCESS
#else	// FLASH_ACCESS
#endif	// FLASH_ACCESS
#ifdef	INCLUDE_ZIPCPU
#ifndef	WBUBUS_MASTER
#endif
#else	// INCLUDE_ZIPCPU
#endif	// INCLUDE_ZIPCPU
#ifdef	RTCDATE_ACCESS
#else	// RTCDATE_ACCESS
#endif	// RTCDATE_ACCESS
#ifdef	WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#else
#endif
#ifndef	BUSPIC_ACCESS
#endif
#else	// WBUBUS_MASTER
#endif	// WBUBUS_MASTER
#ifdef	SDSPI_SCOPE
#else	// SDSPI_SCOPE
#endif	// SDSPI_SCOPE
#ifdef	SDSPI_ACCESS
#else	// SDSPI_ACCESS
#endif	// SDSPI_ACCESS

#endif // DESIGN_H
